# Generated by Django 2.2.4 on 2019-08-24 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='location',
        ),
        migrations.AddField(
            model_name='image',
            name='editor',
            field=models.ForeignKey(default='Joe', on_delete=django.db.models.deletion.CASCADE, to='photos.Editor'),
        ),
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.ForeignKey(default='Joe', on_delete=django.db.models.deletion.CASCADE, to='photos.Category'),
        ),
    ]
