# Generated by Django 2.2.4 on 2019-08-25 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image_category',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='image_location',
            new_name='category',
        ),
    ]
