# Generated by Django 2.2.4 on 2019-08-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='epic',
            new_name='image_category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='food',
        ),
        migrations.RemoveField(
            model_name='category',
            name='heritage',
        ),
        migrations.RemoveField(
            model_name='category',
            name='landscape',
        ),
        migrations.RemoveField(
            model_name='category',
            name='portrait',
        ),
        migrations.RemoveField(
            model_name='category',
            name='travel',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
