# Generated by Django 2.2.4 on 2019-08-25 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20190825_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='location',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='category',
            new_name='location',
        ),
    ]
