# Generated by Django 2.2.4 on 2019-08-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20190824_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.TextField(),
        ),
    ]
