# Generated by Django 2.2.4 on 2019-08-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_remove_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_category',
            field=models.CharField(default='Epic', max_length=50),
        ),
    ]
