# Generated by Django 2.2.4 on 2019-08-25 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20190826_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='Location',
        ),
    ]
