# Generated by Django 2.2.4 on 2019-08-24 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20190824_2212'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Locate',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='image_location',
        ),
        migrations.RemoveField(
            model_name='editor',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='image',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='image',
            name='editor',
        ),
        migrations.AddField(
            model_name='image',
            name='editor',
            field=models.ManyToManyField(to='photos.Editor'),
        ),
    ]
