# Generated by Django 2.2.4 on 2019-08-25 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20190826_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='Location',
            new_name='location',
        ),
    ]
