# Generated by Django 2.2.4 on 2019-08-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20190824_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='email',
            field=models.EmailField(default='Anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='editor',
            name='name',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
